### ISSUE TITLE
M/D: Contact Component

### ISSUE THREAD

**Issue by ErikPlachta** [ErikPlachta/ErikPlachta#35]
## Contact Me section fully up to date, complete, and responsive

- [x] **Build Contact Form**
     - [ ] Design
          - [x] Grab user information
          - [x] Captcha Security / ( _to prevent spam/bots_ ) 
          - [x] Category / ( _what's it about?_ )
          - [x] Hover over form fields gives message of value required
     - [x] Meta
          - [x] `category` 
               - [x] Required Value
               - [x] Options
                    - [x] `collaborate`
                    - [x] `hire me`
                    - [x] `general question`
          - [x] `name`
               - [x] Required Value
               - [x] Data Validation
          - [x] `email` - **Required**
               - [x] Required Value
               - [x] Data Validation
          - [x] `message` - **Required**
               - [x] Required Value
               - [x] Data Validation
               - [ ] Character Limit

**Comment by ErikPlachta** [comment]
Making some progress, here.
